### ISSUE TITLE
Build Compilation failed 

### ISSUE THREAD

**Issue by Mithilesh8789** [gmerabishvili/angular-ng-autocomplete#180]
#### Bug description
Latest version is not working. ng build is failed.

#### Expected result
It should be compatible.

#### Actual result
Error: ./node_modules/angular-ng-autocomplete/fesm2015/angular-ng-autocomplete.mjs 830:206-218
Can't import the named export 'CommonModule' from non EcmaScript module (only default export is available)
    at HarmonyImportSpecifierDependency._getErrors (/usr/src/app/node_modules/webpack/lib/dependencies/HarmonyImportSpecifierDependency.js:88:6)
    at HarmonyImportSpecifierDependency.getErrors (/usr/src/app/node_modules/webpack/lib/dependencies/HarmonyImportSpecifierDependency.js:68:16)
    at Compilation.reportDependencyErrorsAndWarnings (/usr/src/app/node_modules/webpack/lib/Compilation.js:1463:22)
    at /usr/src/app/node_modules/webpack/lib/Compilation.js:1258:10
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/usr/src/app/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:53:1)
    at AsyncSeriesHook.lazyCompileHook (/usr/src/app/node_modules/webpack/node_modules/tapable/lib/Hook.js:154:20)
    at Compilation.finish (/usr/src/app/node_modules/webpack/lib/Compilation.js:1253:28)
    at /usr/src/app/node_modules/webpack/lib/Compiler.js:672:17
    at _done (eval at create (/usr/src/app/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:9:1)
    at eval (eval at create (/usr/src/app/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:36:22)
    at /usr/src/app/node_modules/webpack/lib/Compilation.js:1185:12
    at /usr/src/app/node_modules/webpack/lib/Compilation.js:1097:9
    at processTicksAndRejections (internal/process/task_queues.js:75:11)
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi ./src/main.ts

Error: ./node_modules/angular-ng-autocomplete/fesm2015/angular-ng-autocomplete.mjs 833:16-28
Can't import the named export 'CommonModule' from non EcmaScript module (only default export is available)
    at HarmonyImportSpecifierDependency._getErrors (/usr/src/app/node_modules/webpack/lib/dependencies/HarmonyImportSpecifierDependency.js:88:6)
    at HarmonyImportSpecifierDependency.getErrors (/usr/src/app/node_modules/webpack/lib/dependencies/HarmonyImportSpecifierDependency.js:68:16)
    at Compilation.reportDependencyErrorsAndWarnings (/usr/src/app/node_modules/webpack/lib/Compilation.js:1463:22)
    at /usr/src/app/node_modules/webpack/lib/Compilation.js:1258:10
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/usr/src/app/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:53:1)
    at AsyncSeriesHook.lazyCompileHook (/usr/src/app/node_modules/webpack/node_modules/tapable/lib/Hook.js:154:20)
    at Compilation.finish (/usr/src/app/node_modules/webpack/lib/Compilation.js:1253:28)
    at /usr/src/app/node_modules/webpack/lib/Compiler.js:672:17
    at _done (eval at create (/usr/src/app/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:9:1)
    at eval (eval at create (/usr/src/app/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:36:22)
    at /usr/src/app/node_modules/webpack/lib/Compilation.js:1185:12
    at /usr/src/app/node_modules/webpack/lib/Compilation.js:1097:9
    at processTicksAndRejections (internal/process/task_queues.js:75:11)
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi ./src/main.ts

#### Steps to reproduce

1.
2.
3.
#### Context
It should be compile without any error.

#### Your Environment

* Version used: 
* Browser Name and version:
* Operating System and version:
* Link to your project:

**Comment by gmerabishvili** [comment]
@Mithilesh8789  Try use version 2.0.7

**Comment by gmerabishvili** [comment]
@Mithilesh8789  What version of Angular are you using?
