### ISSUE TITLE
Got warning while ng serve - export 'defineInjectable' was not found in '@angular/core'

### ISSUE THREAD

**Issue by agiratech-venkat** [gmerabishvili/angular-ng-autocomplete#9]
WARNING in ./node_modules/angular-ng-autocomplete/fesm5/angular-ng-autocomplete.js
22:64-80 "export 'defineInjectable' was not found in '@angular/core'
    at HarmonyImportSpecifierDependency._getErrors (/home/venkat/Desktop/Projects/Amn-angualr/node_modules/webpack/lib/dependencies/HarmonyImportSpecifierDependency.js:65:15)
    at HarmonyImportSpecifierDependency.getWarnings (/home/venkat/Desktop/Projects/Amn-angualr/node_modules/webpack/lib/dependencies/HarmonyImportSpecifierDependency.js:39:15)
    at Compilation.reportDependencyErrorsAndWarnings (/home/venkat/Desktop/Projects/Amn-angualr/node_modules/webpack/lib/Compilation.js:694:24)
    at Compilation.finish (/home/venkat/Desktop/Projects/Amn-angualr/node_modules/webpack/lib/Compilation.js:552:9)
    at applyPluginsParallel.err (/home/venkat/Desktop/Projects/Amn-angualr/node_modules/webpack/lib/Compiler.js:512:17)
    at /home/venkat/Desktop/Projects/Amn-angualr/node_modules/tapable/lib/Tapable.js:289:11
    at _addModuleChain (/home/venkat/Desktop/Projects/Amn-angualr/node_modules/webpack/lib/Compilation.js:498:11)
    at processModuleDependencies.err (/home/venkat/Desktop/Projects/Amn-angualr/node_modules/webpack/lib/Compilation.js:468:14)
    at process._tickCallback (internal/process/next_tick.js:61:11)

And in the browser console is I got this error "TypeError: Object(...) is not a function" and app stops working

**Comment by gmerabishvili** [comment]
Which version of Angular are you using?

**Comment by agiratech-venkat** [comment]
Thanls

> Which version of Angular are you using?

Thanks for the quick reply.
I am using Angular 4

**Comment by gmerabishvili** [comment]
I think you must update your angular app to at least angular 6 or angular 7 version. Unfortunately @Injectable, which is new in angular 6 and angular 7  is not backwards compatible with NG 5 and below...
